/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Produccion;

import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Conexion;

/**
 *
 * @author pc
 */
public class DetalleProduProducto extends javax.swing.JPanel {

    private final int idProduccion;
    

    /**
     * Creates new form DetallePdroduProducto
     */
    public DetalleProduProducto(int idProduccion, String nombre, String fechaInicio,
            String fechaFin, String estado, String cantidad, String dimensiones) {
        System.out.println("ID recibido en constructor: " + idProduccion); 
        this.idProduccion = idProduccion;
        initComponents();

        DetallePedido detallePanel = new DetallePedido(
                idProduccion,
                nombre,
                fechaInicio,
                fechaFin,
                estado,
                String.valueOf(cantidad),
                dimensiones
        );
        mostrarPanelSecundario(detallePanel);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnvolver = new RSMaterialComponent.RSButtonShape();
        btnEtapa = new RSMaterialComponent.RSButtonShape();
        btndetalle = new RSMaterialComponent.RSButtonShape();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(242, 247, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 630));

        btnvolver.setBackground(new java.awt.Color(46, 49, 82));
        btnvolver.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/volver (1).png"))); // NOI18N
        btnvolver.setText("Volver");
        btnvolver.setBackgroundHover(new java.awt.Color(67, 150, 209));
        btnvolver.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnvolver.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        btnEtapa.setBackground(new java.awt.Color(46, 49, 82));
        btnEtapa.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnEtapa.setText("Etapa de produccion");
        btnEtapa.setBackgroundHover(new java.awt.Color(67, 150, 209));
        btnEtapa.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btnEtapa.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        btnEtapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEtapaActionPerformed(evt);
            }
        });

        btndetalle.setBackground(new java.awt.Color(46, 49, 82));
        btndetalle.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btndetalle.setText("    Detalle de pedido");
        btndetalle.setBackgroundHover(new java.awt.Color(67, 150, 209));
        btndetalle.setFont(new java.awt.Font("Roboto Bold", 1, 16)); // NOI18N
        btndetalle.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        btndetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndetalleActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(234, 234, 234));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btndetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnvolver, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btndetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEtapa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1186, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        Produccion pr = new Produccion(new javax.swing.JFrame());
        mostrarPanel(pr);
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnEtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEtapaActionPerformed
        
        ProduccionContEtapa etapa = new ProduccionContEtapa(
                this.idProduccion
        );
        mostrarPanelSecundario(etapa);
    }//GEN-LAST:event_btnEtapaActionPerformed

    private void btndetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndetalleActionPerformed
    DetallePedido pedido = new DetallePedido(this.idProduccion);
    mostrarPanelSecundario(pedido);

    }//GEN-LAST:event_btndetalleActionPerformed
    private void mostrarPanelSecundario(JPanel panel) {
        panel.setSize(1250, 690);
        panel.setLocation(0, 0);

        jPanel2.removeAll();
        jPanel2.add(panel);
        jPanel2.revalidate();
        jPanel2.repaint();
    }
    
    private void mostrarPanel(JPanel panel) {
        panel.setSize(1250, 630);
        panel.setLocation(0, 0);

        jPanel1.removeAll();
        jPanel1.add(panel);
        jPanel1.revalidate();
        jPanel1.repaint();
    }


    public void setVolverListener(ActionListener listener) {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShape btnEtapa;
    private RSMaterialComponent.RSButtonShape btndetalle;
    private RSMaterialComponent.RSButtonShape btnvolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
