/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.Produccion;

import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Frame;
import java.awt.image.BufferedImage;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author EQUIPO
 */
public class DetallleEtapa extends javax.swing.JDialog {

    /**
     * Creates new form DetallleEtapa
     */
    public DetallleEtapa(Frame parent, boolean modal, int idEtapa, String nombre1, String cantidad1,
            String fechaInicio, String fechaFin, String estado1,
            Map<String, String> materiales, Map<String, String> herramientas, String asignado1) {
        super(parent, modal);
        initComponents();
        setIconImage(new BufferedImage(1, 1, BufferedImage.TYPE_INT_ARGB_PRE));

        // Asignar valores a componentes básicos
        nombre.setText(nombre1);
        cantidad.setText(cantidad1);
        fecha_ini.setText(fechaInicio);
        fecha_fin.setText(fechaFin);
        estado.setText(estado1);
        asignado.setText(asignado1);

        // Configurar paneles DINÁMICAMENTE
        configurarPaneles(materiales, herramientas);

        setLocationRelativeTo(parent);
    }

    private void configurarPaneles(Map<String, String> materiales, Map<String, String> herramientas) {
        // Configurar panel de materiales
        PanMaterialessss.setLayout(new BoxLayout(PanMaterialessss, BoxLayout.Y_AXIS));
        PanMaterialessss.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(Color.GRAY),
                "Materiales",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new Font("Segoe UI", Font.BOLD, 18) // Tamaño 14 y negrita
        ));
        PanMaterialessss.setBackground(Color.WHITE);
        PanMaterialessss.setPreferredSize(new java.awt.Dimension(350, 200)); // Ancho: 350px, Alto: 200px

        for (Map.Entry<String, String> entry : materiales.entrySet()) {
            JPanel fila = new JPanel(new FlowLayout(FlowLayout.LEFT));
            fila.setBackground(Color.WHITE);

            JLabel lblNombre = new JLabel(entry.getKey() + ": ");
            lblNombre.setFont(new Font("Segoe UI", Font.BOLD, 16));

            JLabel lblCantidad = new JLabel(entry.getValue());
            lblCantidad.setFont(new Font("Segoe UI", Font.PLAIN, 16));

            fila.add(lblNombre);
            fila.add(lblCantidad);
            PanMaterialessss.add(fila);
        }

        // Configurar panel de herramientas
        PanHerramientas.setLayout(new BoxLayout(PanHerramientas, BoxLayout.Y_AXIS));
        PanHerramientas.setBorder(BorderFactory.createTitledBorder(
                BorderFactory.createLineBorder(Color.GRAY),
                "Herramientas",
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new Font("Segoe UI", Font.BOLD, 18) // Tamaño 14 y negrita
        ));
        PanHerramientas.setBackground(Color.WHITE);
        PanHerramientas.setPreferredSize(new java.awt.Dimension(350, 200)); // Ancho: 350px, Alto: 200px

        for (Map.Entry<String, String> entry : herramientas.entrySet()) {
            JPanel fila = new JPanel(new FlowLayout(FlowLayout.LEFT));
            fila.setBackground(Color.WHITE);

            JLabel lblNombre = new JLabel(entry.getKey() + ": ");
            lblNombre.setFont(new Font("Segoe UI", Font.BOLD, 16));

            JLabel lblCantidad = new JLabel(entry.getValue());
            lblCantidad.setFont(new Font("Segoe UI", Font.PLAIN, 16));

            fila.add(lblNombre);
            fila.add(lblCantidad);
            PanHerramientas.add(fila);
        }

        // Ajustar tamaño del diálogo
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fecha_ini = new javax.swing.JLabel();
        fecha_fin = new javax.swing.JLabel();
        cantidad = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        asignado = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar1 = new rojeru_san.RSButtonRiple();
        PanHerramientas = new javax.swing.JPanel();
        PanMaterialessss = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nombre:");

        fecha_ini.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fecha_ini.setText("fecha_ini");

        fecha_fin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        fecha_fin.setText("fecha_fin");

        cantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cantidad.setText("cantidad");

        estado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        estado.setText("estado");

        nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nombre.setText("Nombre");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Fecha de final:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Cantidad:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Estado:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Fecha de inicio: ");

        asignado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        asignado.setText("asignado");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("Asignado:");

        jPanel4.setBackground(new java.awt.Color(46, 49, 82));

        jLabel2.setFont(new java.awt.Font("Century751 BT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Etapa Produccion");

        btnGuardar1.setBackground(new java.awt.Color(46, 49, 82));
        btnGuardar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x.png"))); // NOI18N
        btnGuardar1.setColorHover(new java.awt.Color(204, 0, 0));
        btnGuardar1.setFont(new java.awt.Font("Humnst777 BlkCn BT", 1, 18)); // NOI18N
        btnGuardar1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(495, 495, 495)
                .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2))
            .addComponent(btnGuardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        PanHerramientas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanHerramientasLayout = new javax.swing.GroupLayout(PanHerramientas);
        PanHerramientas.setLayout(PanHerramientasLayout);
        PanHerramientasLayout.setHorizontalGroup(
            PanHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
        );
        PanHerramientasLayout.setVerticalGroup(
            PanHerramientasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        PanMaterialessss.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanMaterialessssLayout = new javax.swing.GroupLayout(PanMaterialessss);
        PanMaterialessss.setLayout(PanMaterialessssLayout);
        PanMaterialessssLayout.setHorizontalGroup(
            PanMaterialessssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanMaterialessssLayout.setVerticalGroup(
            PanMaterialessssLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(PanMaterialessss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16)
                        .addComponent(nombre))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(15, 15, 15)
                        .addComponent(fecha_ini)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)
                        .addGap(15, 15, 15)
                        .addComponent(cantidad)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel17)
                        .addGap(10, 10, 10)
                        .addComponent(asignado))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(28, 28, 28)
                        .addComponent(fecha_fin)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel13)
                        .addGap(12, 12, 12)
                        .addComponent(estado))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(nombre))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(fecha_ini)
                    .addComponent(jLabel5)
                    .addComponent(cantidad)
                    .addComponent(jLabel17)
                    .addComponent(asignado))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(fecha_fin)
                    .addComponent(jLabel13)
                    .addComponent(estado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanMaterialessss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        this.dispose();

    }//GEN-LAST:event_btnGuardar1ActionPerformed

    /**
     * @param args the command line arguments
     *
     *
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanHerramientas;
    private javax.swing.JPanel PanMaterialessss;
    private javax.swing.JLabel asignado;
    private rojeru_san.RSButtonRiple btnGuardar1;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel fecha_fin;
    private javax.swing.JLabel fecha_ini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
