/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.Produccion;

/**
 *
 * @author EQUIPO
 */
public class ProduccionPrinci extends javax.swing.JPanel {

    /**
     * Creates new form ProduccionPrinci
     */
    public ProduccionPrinci() {
        initComponents();
        this.Produccion.setSelected(true);

        Produccion pr = new Produccion(new javax.swing.JFrame(), true);
        pr.setSize(1290, 730);
        pr.setLocation(0, 0);

        conteiner.removeAll();
        conteiner.add(pr);
        conteiner.revalidate();
        conteiner.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Produccion = new RSMaterialComponent.RSButtonShape();
        Etapa = new RSMaterialComponent.RSButtonShape();
        conteiner = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1290, 730));

        Produccion.setBackground(new java.awt.Color(46, 49, 82));
        Produccion.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Produccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productivity.png"))); // NOI18N
        Produccion.setText(" Produccion");
        Produccion.setBackgroundHover(new java.awt.Color(67, 150, 209));
        Produccion.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        Produccion.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        Produccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProduccionActionPerformed(evt);
            }
        });

        Etapa.setBackground(new java.awt.Color(46, 49, 82));
        Etapa.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Etapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gears-set.png"))); // NOI18N
        Etapa.setText("Etapa produccion");
        Etapa.setBackgroundHover(new java.awt.Color(67, 150, 209));
        Etapa.setFont(new java.awt.Font("Roboto Bold", 1, 18)); // NOI18N
        Etapa.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        Etapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtapaActionPerformed(evt);
            }
        });

        conteiner.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout conteinerLayout = new javax.swing.GroupLayout(conteiner);
        conteiner.setLayout(conteinerLayout);
        conteinerLayout.setHorizontalGroup(
            conteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        conteinerLayout.setVerticalGroup(
            conteinerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Produccion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Etapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(897, Short.MAX_VALUE))
            .addComponent(conteiner, javax.swing.GroupLayout.DEFAULT_SIZE, 1290, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Produccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Etapa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(conteiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProduccionActionPerformed
        if (!this.Produccion.isSelected()) {
            deseleccionar();
            this.Produccion.setSelected(true);

            Produccion pr = new Produccion(new javax.swing.JFrame(), true);
            pr.setSize(1290, 730);
            pr.setLocation(0, 0);

            conteiner.removeAll();
            conteiner.add(pr);
            conteiner.revalidate();
            conteiner.repaint();

        }
    }//GEN-LAST:event_ProduccionActionPerformed

    private void EtapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtapaActionPerformed
        if (!this.Etapa.isSelected()) {

            this.Etapa.setSelected(true);
            Produccion pr = new Produccion(new javax.swing.JFrame(), true);
            pr.setSize(1290, 730);
            pr.setLocation(0, 0);

            conteiner.removeAll();
            conteiner.add(pr);
            conteiner.revalidate();
            conteiner.repaint();

        }
    }//GEN-LAST:event_EtapaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShape Etapa;
    private RSMaterialComponent.RSButtonShape Produccion;
    private javax.swing.JPanel conteiner;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void deseleccionar() {
        this.Produccion.setSelected(false);
        this.Etapa.setSelected(false);
    }
}
