/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author buitr
 */
public class config extends javax.swing.JPanel {

    /**
     * Creates new form config
     */
    public config() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAñadir5 = new RSMaterialComponent.RSButtonShape();
        btnAñadir6 = new RSMaterialComponent.RSButtonShape();
        btnAñadir7 = new RSMaterialComponent.RSButtonShape();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnAñadir5.setBackground(new java.awt.Color(46, 49, 82));
        btnAñadir5.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnAñadir5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informacion 24px.png"))); // NOI18N
        btnAñadir5.setText("Ayuda");
        btnAñadir5.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnAñadir5.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        btnAñadir5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadir5ActionPerformed(evt);
            }
        });
        add(btnAñadir5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 310, 70));

        btnAñadir6.setBackground(new java.awt.Color(46, 49, 82));
        btnAñadir6.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnAñadir6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/llave 24px.png"))); // NOI18N
        btnAñadir6.setText("Cambiar Contraseña");
        btnAñadir6.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnAñadir6.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        btnAñadir6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadir6ActionPerformed(evt);
            }
        });
        add(btnAñadir6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 180, 70));

        btnAñadir7.setBackground(new java.awt.Color(46, 49, 82));
        btnAñadir7.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btnAñadir7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/disco 24px.png"))); // NOI18N
        btnAñadir7.setText("Copia de Seguridad");
        btnAñadir7.setBackgroundHover(new java.awt.Color(0, 153, 0));
        btnAñadir7.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        btnAñadir7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadir7ActionPerformed(evt);
            }
        });
        add(btnAñadir7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 180, 70));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadir5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadir5ActionPerformed
        
    }//GEN-LAST:event_btnAñadir5ActionPerformed

    private void btnAñadir6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadir6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadir6ActionPerformed

    private void btnAñadir7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadir7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAñadir7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShape btnAñadir;
    private RSMaterialComponent.RSButtonShape btnAñadir1;
    private RSMaterialComponent.RSButtonShape btnAñadir2;
    private RSMaterialComponent.RSButtonShape btnAñadir3;
    private RSMaterialComponent.RSButtonShape btnAñadir4;
    private RSMaterialComponent.RSButtonShape btnAñadir5;
    private RSMaterialComponent.RSButtonShape btnAñadir6;
    private RSMaterialComponent.RSButtonShape btnAñadir7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
