/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import static com.mysql.cj.protocol.x.XProtocolDecoder.instance;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class formuProduccion extends javax.swing.JFrame {

    private Produccion produccion;

    /**
     * Creates new form formuProduccion
     */
    public formuProduccion(Produccion produccion) {
        this.produccion = produccion; // Inicializa la referencia
        initComponents();
    }

    private void GuardarProdActionPerformed(java.awt.event.ActionEvent evt) {                                            
    String inicio = txt_ini.getText();
    String finall = txt_final.getText();
    String estado = (String) estadoPro.getSelectedItem();

    // Validar que los campos obligatorios no estén vacíos
    if (inicio.isEmpty() || finall.isEmpty() || estado == null) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos obligatorios.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Agregar la fila a la tabla en Produccion
    produccion.agregarFila("", inicio, finall, estado); // El primer parámetro es el ID, que se genera aleatoriamente en Produccion

    // Limpiar los campos después de guardar
    txt_ini.setText("");
    txt_final.setText("");
    estadoPro.setSelectedIndex(0);

    // Opcional: cerrar el formulario actual
    dispose();

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelP = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_ini = new RSMaterialComponent.RSTextFieldMaterial();
        txt_final = new RSMaterialComponent.RSTextFieldMaterial();
        cancelProduc = new rojeru_san.RSButtonRiple();
        GuardarPro = new rojeru_san.RSButtonRiple();
        jLabel5 = new javax.swing.JLabel();
        estadoPro = new RSMaterialComponent.RSComboBoxMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelP.setBackground(new java.awt.Color(255, 255, 255));
        panelP.setPreferredSize(new java.awt.Dimension(500, 500));
        panelP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 49, 82));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century751 BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Produccion");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        panelP.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Fecha inicio:");
        panelP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Fecha final:");
        panelP.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        txt_ini.setForeground(new java.awt.Color(0, 0, 0));
        txt_ini.setColorMaterial(new java.awt.Color(0, 0, 0));
        txt_ini.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_ini.setPhColor(new java.awt.Color(0, 0, 0));
        txt_ini.setPlaceholder("Ingrese fecha inicio...");
        txt_ini.setSelectionColor(new java.awt.Color(0, 0, 0));
        panelP.add(txt_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 30));

        txt_final.setForeground(new java.awt.Color(0, 0, 0));
        txt_final.setColorMaterial(new java.awt.Color(0, 0, 0));
        txt_final.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_final.setPhColor(new java.awt.Color(0, 0, 0));
        txt_final.setPlaceholder("Ingrese fecha final...");
        txt_final.setSelectionColor(new java.awt.Color(0, 0, 0));
        txt_final.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_finalActionPerformed(evt);
            }
        });
        panelP.add(txt_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 200, 30));

        cancelProduc.setBackground(new java.awt.Color(46, 49, 82));
        cancelProduc.setText("Cancelar");
        cancelProduc.setColorHover(new java.awt.Color(204, 0, 0));
        cancelProduc.setFont(new java.awt.Font("Humnst777 BlkCn BT", 1, 14)); // NOI18N
        cancelProduc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelProducActionPerformed(evt);
            }
        });
        panelP.add(cancelProduc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 140, -1));

        GuardarPro.setBackground(new java.awt.Color(46, 49, 82));
        GuardarPro.setText("Guardar");
        GuardarPro.setColorHover(new java.awt.Color(0, 153, 51));
        GuardarPro.setFont(new java.awt.Font("Humnst777 BlkCn BT", 1, 14)); // NOI18N
        GuardarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarProActionPerformed(evt);
            }
        });
        panelP.add(GuardarPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 140, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Estado:");
        panelP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        estadoPro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Estado...", "Por iniciar", "En proceso ", "Finalizado", " " }));
        estadoPro.setColorMaterial(new java.awt.Color(0, 0, 0));
        estadoPro.setFont(new java.awt.Font("Roboto Bold", 0, 14)); // NOI18N
        estadoPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoProActionPerformed(evt);
            }
        });
        panelP.add(estadoPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelP, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelP, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_finalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_finalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_finalActionPerformed

    private void cancelProducActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelProducActionPerformed

    }//GEN-LAST:event_cancelProducActionPerformed

    private void GuardarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarProActionPerformed

    }//GEN-LAST:event_GuardarProActionPerformed

    private void estadoProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoProActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple GuardarPro;
    private rojeru_san.RSButtonRiple cancelProduc;
    private RSMaterialComponent.RSComboBoxMaterial estadoPro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelP;
    private RSMaterialComponent.RSTextFieldMaterial txt_final;
    private RSMaterialComponent.RSTextFieldMaterial txt_ini;
    // End of variables declaration//GEN-END:variables
}
