
package vista;
import vista.alertas.LoginAlertaContrasenaIncorrecta;
import vista.alertas.LoginAlertaContrasena;
import vista.alertas.LoginAlerta;
import vista.alertas.LoginAlertaUsuario;
import controlador.Contrl_login;
import java.awt.BorderLayout;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.UsuarioModelo;




public class Login11211 extends javax.swing.JFrame {
 private boolean isPasswordVisible = false;
    private final String eyeOpenPath = "/vista (1).png";   // Ojo abierto
    private final String eyeClosedPath = "/ojo (2).png"; // Ojo cerrado
    
    private ImageIcon eyeOpenIcon;
    private ImageIcon eyeClosedIcon;
  


    public Login11211() {
        initComponents();
    setExtendedState(JFrame.MAXIMIZED_BOTH); 
setLocationRelativeTo(null); 
txt_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            passtxt.requestFocus();
        }
    }
});


passtxt.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyPressed(java.awt.event.KeyEvent evt) {
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            iniciar.doClick(); 
        }
    }
});



setLayout(new GridBagLayout());
GridBagConstraints gbc = new GridBagConstraints();
gbc.gridx = 0;
gbc.gridy = 0;
gbc.anchor = GridBagConstraints.CENTER; 
add(kGradientPanel1, gbc);


JPanel fondo = new JPanel(new BorderLayout());
fondo.add(kGradientPanel1, BorderLayout.CENTER);
setContentPane(fondo);


    }
    
    private void togglePasswordVisibility() {
        if (isPasswordVisible) {
            passtxt.setEchoChar('•'); // Ocultar contraseña
            btnVer.setIcon(eyeClosedIcon); // Cambiar a imagen de ojo cerrado

        } else {
            passtxt.setEchoChar((char) 0); // Mostrar contraseña
            btnVer.setIcon(eyeOpenIcon); // Cambiar a imagen de ojo abierto
        }
        isPasswordVisible = !isPasswordVisible;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel7 = new javax.swing.JLabel();
        txt_usuario = new RSMaterialComponent.RSTextFieldIconOne();
        jLabel6 = new javax.swing.JLabel();
        passtxt = new RSMaterialComponent.RSPasswordIconOne();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        iniciar = new RSMaterialComponent.RSButtonShape();
        btnVer = new rojeru_san.RSButton();
        rSButtonRound1 = new rojerusan.RSButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(239, 248, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(254, 254, 254));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo_azul.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        kGradientPanel1.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 180, 140));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setText("Usuario");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 90, 20));

        txt_usuario.setForeground(new java.awt.Color(0, 0, 0));
        txt_usuario.setBorderColor(new java.awt.Color(230, 230, 230));
        txt_usuario.setColorIcon(new java.awt.Color(204, 204, 204));
        txt_usuario.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        txt_usuario.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        txt_usuario.setPhColor(new java.awt.Color(51, 51, 51));
        txt_usuario.setPlaceholder("ingrese su usuario");
        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        kGradientPanel1.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 390, 30));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setText("Contraseña");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 120, 20));

        passtxt.setForeground(new java.awt.Color(0, 0, 0));
        passtxt.setToolTipText("");
        passtxt.setBorderColor(new java.awt.Color(230, 230, 230));
        passtxt.setColorIcon(new java.awt.Color(204, 204, 204));
        passtxt.setPhColor(new java.awt.Color(51, 51, 51));
        passtxt.setPlaceholder("Ingrese su contraseña");
        passtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtxtActionPerformed(evt);
            }
        });
        kGradientPanel1.add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 390, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(29, 30, 51));
        jLabel2.setText("¿Olvidaste contraseña?");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 190, 20));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 39)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(29, 30, 51));
        jLabel13.setText("Iniciar Sesión");
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 260, 50));

        iniciar.setBackground(new java.awt.Color(29, 30, 51));
        iniciar.setText("                                               Ingresar");
        iniciar.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        kGradientPanel1.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 570, 390, 50));

        btnVer.setBackground(new java.awt.Color(236, 236, 236));
        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ojo (2).png"))); // NOI18N
        btnVer.setColorHover(new java.awt.Color(247, 247, 247));
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 480, 40, 30));

        rSButtonRound1.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonRound1.setText("rSButtonRound1");
        rSButtonRound1.setColorHover(new java.awt.Color(255, 255, 255));
        kGradientPanel1.add(rSButtonRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 550, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
         
         cargando11 cargando = new cargando11(new JFrame(), true);

        new Thread(() -> {
            cargando.setVisible(true);
        }).start();

        javax.swing.Timer timer = new javax.swing.Timer(2000, e -> {
            cargando.dispose();

        });

        timer.setRepeats(false); // Solo una vez
        timer.start();
        Correo_electronico dialog = new Correo_electronico();
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
     
        this.dispose(); // Cierra el login


        this.dispose();

    }//GEN-LAST:event_jLabel2MousePressed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
       autenticarUsuario();
    }//GEN-LAST:event_iniciarActionPerformed

    private void passtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtxtActionPerformed

    }//GEN-LAST:event_passtxtActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        togglePasswordVisibility();
    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login11211.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login11211.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login11211.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login11211.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login11211().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnVer;
    private RSMaterialComponent.RSButtonShape iniciar;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private keeptoo.KGradientPanel kGradientPanel1;
    private RSMaterialComponent.RSPasswordIconOne passtxt;
    private rojerusan.RSButtonRound rSButtonRound1;
    private rojerusan.RSPanelImage rSPanelImage1;
    private RSMaterialComponent.RSTextFieldIconOne txt_usuario;
    // End of variables declaration//GEN-END:variables

    
  private void autenticarUsuario() {
    String nombreUsuario = txt_usuario.getText().trim();
    String contrasena = new String(passtxt.getPassword()).trim();

    if (nombreUsuario.isEmpty() && contrasena.isEmpty()) {
        LoginAlerta confirmDialog = new LoginAlerta(
                (Frame) this.getParent(),
                true,
                "Confirmar",
                "¿Desea guardar los datos?"
        );
        confirmDialog.setVisible(true);
        return;
    } else if (nombreUsuario.isEmpty()) {
        LoginAlertaUsuario confirmDialog = new LoginAlertaUsuario(
                (Frame) this.getParent(),
                true,
                "Confirmar",
                "¿Desea guardar los datos?"
        );
        confirmDialog.setVisible(true);
        return;
    } else if (contrasena.isEmpty()) {
        LoginAlertaContrasena confirmDialog = new LoginAlertaContrasena(
                (Frame) this.getParent(),
                true,
                "Confirmar",
                "¿Desea guardar los datos?"
        );
        confirmDialog.setVisible(true);
        return;
    }

    Contrl_login controlUsuario = new Contrl_login();
    modelo.UsuarioModelo usuario = new modelo.UsuarioModelo();
    usuario.setUsuario(nombreUsuario);
    usuario.setContrasena(contrasena);

    // Obtener el usuario autenticado
    UsuarioModelo usuarioAutenticado = controlUsuario.loginUser(usuario);

    if (usuarioAutenticado != null) {
        JOptionPane.showMessageDialog(null, "Inicio de sesión exitoso", "Bienvenido", JOptionPane.INFORMATION_MESSAGE);

        // Mostrar pantalla de carga
       // kla cargando = new kla(false);
       // new Thread(() -> cargando.setVisible(true)).start();

        // Guardar el idUsuario para usarlo en otras vistas
        int idUsuario = usuarioAutenticado.getId_usuario();

        javax.swing.Timer timer = new javax.swing.Timer(2000, e -> {
         //   cargando.dispose();
            // Pasar el idUsuario a Principal1
            Principal111 principal = new Principal111(idUsuario);
            principal.setVisible(true);
            this.dispose();
        });

        timer.setRepeats(false);
        timer.start();
    } else {
        LoginAlertaContrasenaIncorrecta confirmDialog = new LoginAlertaContrasenaIncorrecta(
                (Frame) this.getParent(),
                true,
                "Confirmar",
                "¿Desea guardar los datos?"
        );
        confirmDialog.setVisible(true);
    }
}

}
