/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZenBook
 */
public class movimientos extends javax.swing.JPanel {
private DefaultTableModel modeloTabla;
    /**
     * Creates new form movimientos
     */
    public movimientos() {
        initComponents();
             tablaM.setBackground(new Color(245,246,250)); // Blanco grisáceo
     tablaM.setOpaque(true);
     tablaM.setFillsViewportHeight(true); // Ajusta el fondo en toda la tabla
        
     tablaM.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        
     modeloTabla = new DefaultTableModel(){
    @Override
    public boolean isCellEditable(int row, int column) {
        return false; // Evita la edición en todas las celdas
    }
};
     modeloTabla.setColumnIdentifiers(new String[]{"Fecha y Hora", "Tipo", "Categoría", "Nombre", "Cantidad", "Responsable", "Motivo"});
     tablaM.setModel(modeloTabla);
    }
    
    
        
    private void agregarFilaATabla(String[] datos) {
    modeloTabla.addRow(datos);
}

private void eliminarMovimientos() {
    int[] filasSeleccionadas = tablaM.getSelectedRows();

    if (filasSeleccionadas.length > 0) {
        int confirmacion = JOptionPane.showConfirmDialog(
            null,
            "¿Está seguro de que desea eliminar los movimientos seleccionados?",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION
        );

        if (confirmacion == JOptionPane.YES_OPTION) {
            DefaultTableModel modelo = (DefaultTableModel) tablaM.getModel();

            // Eliminar desde la última fila seleccionada para evitar problemas de índice
            for (int i = filasSeleccionadas.length - 1; i >= 0; i--) {
                modelo.removeRow(filasSeleccionadas[i]);
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Seleccione al menos una fila para eliminar.");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtBuscar = new RSMaterialComponent.RSTextFieldMaterialIcon();
        rSComboMetro1 = new rojerusan.RSComboMetro();
        btnEliminar = new rojeru_san.RSButtonRiple();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaM = new RSMaterialComponent.RSTableMetroCustom();
        btnNuevo = new rojeru_san.RSButtonRiple();
        btnEditar = new rojeru_san.RSButtonRiple();

        setPreferredSize(new java.awt.Dimension(1240, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(237, 241, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1240, 580));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setForeground(new java.awt.Color(0, 0, 0));
        txtBuscar.setColorIcon(new java.awt.Color(0, 0, 0));
        txtBuscar.setColorMaterial(new java.awt.Color(153, 153, 153));
        txtBuscar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        txtBuscar.setPhColor(new java.awt.Color(102, 102, 102));
        txtBuscar.setPlaceholder("Buscar...");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 30));

        rSComboMetro1.setColorArrow(new java.awt.Color(0, 0, 0));
        rSComboMetro1.setColorBorde(new java.awt.Color(255, 255, 255));
        rSComboMetro1.setColorFondo(new java.awt.Color(255, 255, 255));
        jPanel1.add(rSComboMetro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, 30));

        btnEliminar.setBackground(new java.awt.Color(46, 49, 82));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/delete (1).png"))); // NOI18N
        btnEliminar.setText(" Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 30, 110, 30));

        tablaM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "2/03/25 4:06 pm", "Entrada", "Materiales", "Pegante",  new Integer(1), "Pegantes S.A.S", "compra"},
                { new Integer(2), "2/03/25 4:11 pm", "Salida", "Materiales", "Madera mdf",  new Integer(3), "Juan Perez", "Uso en fabricacion"},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Fecha y hora", "Tipo", "Categoria", "Nombre", "Cantidad", "Responsable", "Motivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaM.setBackgoundHead(new java.awt.Color(46, 49, 82));
        tablaM.setBackgoundHover(new java.awt.Color(67, 150, 209));
        tablaM.setBorderHead(null);
        tablaM.setBorderRows(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tablaM.setColorBorderHead(new java.awt.Color(46, 49, 82));
        tablaM.setColorBorderRows(new java.awt.Color(46, 49, 82));
        tablaM.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tablaM.setColorSecondary(new java.awt.Color(255, 255, 255));
        tablaM.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        tablaM.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tablaM.setFontHead(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tablaM.setFontRowHover(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tablaM.setFontRowSelect(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tablaM.setSelectionBackground(new java.awt.Color(67, 150, 209));
        jScrollPane2.setViewportView(tablaM);
        tablaM.getColumnModel().getColumn(0).setPreferredWidth(10);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 1140, 420));

        btnNuevo.setBackground(new java.awt.Color(46, 49, 82));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus (2).png"))); // NOI18N
        btnNuevo.setText(" Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 100, 30));

        btnEditar.setBackground(new java.awt.Color(46, 49, 82));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pencil (1).png"))); // NOI18N
        btnEditar.setText(" Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 30, 100, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
    nuevoMovimiento dialog = new nuevoMovimiento(new javax.swing.JFrame(), true);
    dialog.setLocationRelativeTo(null);
    dialog.setVisible(true);

    if (dialog.isGuardado()) {
        String[] datos = dialog.getDatos();
        agregarFilaATabla(datos);
    }
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
int filaSeleccionada = tablaM.getSelectedRow();
if (filaSeleccionada >= 0) {
    String[] datosFila = new String[7];
    for (int i = 0; i < 7; i++) {
        datosFila[i] = (String) tablaM.getValueAt(filaSeleccionada, i);
    }
    
    movimientoEditar dialogoEditar = new movimientoEditar(null, true);
    dialogoEditar.cargarDatos(datosFila);
    dialogoEditar.setLocationRelativeTo(null);
    dialogoEditar.setVisible(true);
    
    if (dialogoEditar.isGuardado()) {
        String[] nuevosDatos = dialogoEditar.getDatos();
        for (int i = 0; i < 7; i++) {
            tablaM.setValueAt(nuevosDatos[i], filaSeleccionada, i);
        }
    }
} else {
    JOptionPane.showMessageDialog(null, "Seleccione una fila para editar.");
}
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnEditar;
    private rojeru_san.RSButtonRiple btnEliminar;
    private rojeru_san.RSButtonRiple btnNuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSComboMetro rSComboMetro1;
    private RSMaterialComponent.RSTableMetroCustom tablaM;
    private RSMaterialComponent.RSTextFieldMaterialIcon txtBuscar;
    // End of variables declaration//GEN-END:variables
}
