/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

//import controlador.Contrl_login;
import vista.alertas.AlertaUsuarioE;
import vista.alertas.AlertaReestablecerContrasena;
import controlador.Contrl_login;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Consulta_Usuarios;

import vista.alertas.AlertaCambioContraseña;

/**
 *
 * @author Personal
 */
public class NuevaContrasena extends javax.swing.JFrame {

    private String correoIngresado = "";
    private boolean isPasswordVisible = false;

    public void setCorreoIngresado(String correo) {
        this.correoIngresado = correo;
    }
    // Rutas de las imágenes
    private final String eyeOpenPath = "/vista (1).png";   // Ojo abierto
    private final String eyeClosedPath = "/ojo (2).png"; // Ojo cerrado

    private ImageIcon eyeOpenIcon;
    private ImageIcon eyeClosedIcon;

    public NuevaContrasena() {
        initComponents();

        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);

        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.CENTER;
        add(kGradientPanel1, gbc);

        JPanel fondo = new JPanel(new BorderLayout());
        fondo.add(kGradientPanel1, BorderLayout.CENTER);
        setContentPane(fondo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jPanel6 = new javax.swing.JPanel();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        iniciar = new RSMaterialComponent.RSButtonShape();
        txtcontrasenanueva = new RSMaterialComponent.RSPasswordIconOne();
        btnVer = new rojeru_san.RSButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setBackground(new java.awt.Color(153, 255, 51));
        kGradientPanel1.setForeground(new java.awt.Color(255, 204, 204));
        kGradientPanel1.setkEndColor(new java.awt.Color(239, 248, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(254, 254, 254));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/logo_azul.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelImage1Layout = new javax.swing.GroupLayout(rSPanelImage1);
        rSPanelImage1.setLayout(rSPanelImage1Layout);
        rSPanelImage1Layout.setHorizontalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );
        rSPanelImage1Layout.setVerticalGroup(
            rSPanelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel6.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 130, 120));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel11.setText("Cambia tu contraseña");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel7.setText("Contraseña");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel8.setText("volver al inicio de sesion");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 170, 20));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel9.setText("Escribe tu nueva contraseña, recuerda que debe tener");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 410, 20));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        jLabel10.setText("8 digitos");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 410, 20));

        iniciar.setBackground(new java.awt.Color(29, 30, 51));
        iniciar.setText("                                                   Continuar");
        iniciar.setForma(RSMaterialComponent.RSButtonShape.FORMA.ROUND);
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        jPanel6.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 410, 40));

        txtcontrasenanueva.setForeground(new java.awt.Color(0, 0, 0));
        txtcontrasenanueva.setToolTipText("");
        txtcontrasenanueva.setBorderColor(new java.awt.Color(230, 230, 230));
        txtcontrasenanueva.setColorIcon(new java.awt.Color(204, 204, 204));
        txtcontrasenanueva.setPhColor(new java.awt.Color(51, 51, 51));
        txtcontrasenanueva.setPlaceholder("Ingrese su contraseña");
        txtcontrasenanueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontrasenanuevaActionPerformed(evt);
            }
        });
        jPanel6.add(txtcontrasenanueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 390, 40));

        btnVer.setBackground(new java.awt.Color(236, 236, 236));
        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ojo (2).png"))); // NOI18N
        btnVer.setColorHover(new java.awt.Color(247, 247, 247));
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        jPanel6.add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 30, 40));

        kGradientPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 470, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed

    }//GEN-LAST:event_jLabel8MousePressed

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        String nuevaContrasena = txtcontrasenanueva.getText().trim();

        if (nuevaContrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese una nueva contraseña.");
            return;
        }

        String regex = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\W).{8,}$";
        if (!nuevaContrasena.matches(regex)) {
            AlertaReestablecerContrasena confirmDialog = new AlertaReestablecerContrasena(
                    (Frame) this.getParent(),
                    true,
                    "Confirmar",
                    "¿Desea guardar los datos?"
            );
            confirmDialog.setVisible(true);
            return;
        }

        Consulta_Usuarios controlador = new Consulta_Usuarios();
        boolean cambioExitoso = controlador.actualizarContrasena(correoIngresado, nuevaContrasena);
        if (cambioExitoso) {
            AlertaCambioContraseña confirmDialog = new AlertaCambioContraseña(
                    (Frame) this.getParent(),
                    true,
                    "Confirmar",
                    "¿Desea guardar los datos?"
            );
            confirmDialog.setVisible(true);
            this.dispose();
            Login1121 login = new Login1121();
            login.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el usuario. Intenta de nuevo.");
            AlertaUsuarioE usu = new AlertaUsuarioE(
                    (Frame) this.getParent(),
                    true,
                    "Confirmar",
                    "¿Desea guardar los datos?"
            );
            usu.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_iniciarActionPerformed

    private void txtcontrasenanuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontrasenanuevaActionPerformed

    }//GEN-LAST:event_txtcontrasenanuevaActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        togglePasswordVisibility();
    }//GEN-LAST:event_btnVerActionPerformed

    /**
     * @param context
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Correo_electronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Correo_electronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Correo_electronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Correo_electronico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButton btnVer;
    private RSMaterialComponent.RSButtonShape iniciar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private rojerusan.RSPanelImage rSPanelImage1;
    private RSMaterialComponent.RSPasswordIconOne txtcontrasenanueva;
    // End of variables declaration//GEN-END:variables

      private void togglePasswordVisibility() {
        if (isPasswordVisible) {
            txtcontrasenanueva.setEchoChar('•'); // Ocultar contraseña
            btnVer.setIcon(eyeClosedIcon); // Cambiar a imagen de ojo cerrado

        } else {
            txtcontrasenanueva.setEchoChar((char) 0); // Mostrar contraseña
            btnVer.setIcon(eyeOpenIcon); // Cambiar a imagen de ojo abierto
        }
        isPasswordVisible = !isPasswordVisible;
    }
  

}
