



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.util.Random;

/**
 *
 * @author pc
 */
public class Produccion extends javax.swing.JPanel {

    /**
     * Creates new form Produccion
     */
    public Produccion() {
        initComponents();
            jScrollPane2.setVisible(true); // Ocultar la tabla 1 inicialmente
            jScrollPane3.setVisible(false); // Ocultar la tabla 1 inicialmente
            jScrollPane4.setVisible(false); // Ocultar la tabla 1 inicialmente
// Agregar DocumentListener a la barra de búsqueda
    rSTextFieldMaterialIcon1.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) {
            filterTables();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            filterTables();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            filterTables();
        }
    });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        rSButtonFlat_new1 = new newscomponents.RSButtonFlat_new();
        rSButtonFlat_new2 = new newscomponents.RSButtonFlat_new();
        rSButtonFlat_new3 = new newscomponents.RSButtonFlat_new();
        rSButtonMaterialTwo3 = new RSMaterialComponent.RSButtonMaterialTwo();
        rSButtonMaterialTwo1 = new RSMaterialComponent.RSButtonMaterialTwo();
        rSTextFieldMaterialIcon1 = new RSMaterialComponent.RSTextFieldMaterialIcon();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla1 = new RSMaterialComponent.RSTableMetroCustom();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla2 = new RSMaterialComponent.RSTableMetroCustom();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla3 = new RSMaterialComponent.RSTableMetroCustom();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1290, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 111, -1, -1));

        rSButtonFlat_new1.setBackground(new java.awt.Color(109, 160, 221));
        rSButtonFlat_new1.setText("Detalle produccion");
        rSButtonFlat_new1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonFlat_new1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonFlat_new1, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 42, 130, -1));

        rSButtonFlat_new2.setBackground(new java.awt.Color(109, 160, 221));
        rSButtonFlat_new2.setText("Etapa produccion");
        rSButtonFlat_new2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonFlat_new2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonFlat_new2, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 42, 126, -1));

        rSButtonFlat_new3.setBackground(new java.awt.Color(109, 160, 221));
        rSButtonFlat_new3.setText("Produccion");
        rSButtonFlat_new3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonFlat_new3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonFlat_new3, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 42, 91, -1));

        rSButtonMaterialTwo3.setBackground(new java.awt.Color(29, 30, 51));
        rSButtonMaterialTwo3.setText("Eliminar -");
        rSButtonMaterialTwo3.setBackgroundHover(new java.awt.Color(29, 30, 31));
        rSButtonMaterialTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialTwo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 86, 37));

        rSButtonMaterialTwo1.setBackground(new java.awt.Color(29, 30, 51));
        rSButtonMaterialTwo1.setText("Nuevo +");
        rSButtonMaterialTwo1.setBackgroundHover(new java.awt.Color(29, 30, 31));
        rSButtonMaterialTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialTwo1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 86, 37));

        rSTextFieldMaterialIcon1.setForeground(new java.awt.Color(29, 30, 91));
        rSTextFieldMaterialIcon1.setColorIcon(new java.awt.Color(29, 30, 111));
        rSTextFieldMaterialIcon1.setColorMaterial(new java.awt.Color(29, 30, 111));
        rSTextFieldMaterialIcon1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSTextFieldMaterialIcon1.setPlaceholder("Buscar");
        rSTextFieldMaterialIcon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSTextFieldMaterialIcon1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSTextFieldMaterialIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 28));

        Tabla1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "43", "34/54/3", "4", "final"},
                {"2", "75", "78/45/23", "2", "proceso"},
                {"3", "45", "54/7/34", "3", "xd"},
                {"4", "73", "23/34/54", "1", "ya"},
                {"5", "67", "45/6/45", "1", "ok"}
            },
            new String [] {
                "#", "ID", "Fecha_inicio", "Fecha_final", "estado"
            }
        ));
        Tabla1.setBackgoundHead(new java.awt.Color(29, 30, 51));
        Tabla1.setBackgoundHover(new java.awt.Color(29, 30, 51));
        Tabla1.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        Tabla1.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        Tabla1.setSelectionBackground(new java.awt.Color(29, 30, 91));
        jScrollPane2.setViewportView(Tabla1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 1220, 520));

        Tabla2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "43", "silla", "4"},
                {"2", "75", "mesa", "2"},
                {"3", "45", "mueble ", "3"},
                {"4", "73", "armario", "1"},
                {"5", "67", "cama", "1"}
            },
            new String [] {
                "#", "Cantidad", "Dimensiones ", "Materiales_usados"
            }
        ));
        Tabla2.setBackgoundHead(new java.awt.Color(29, 30, 51));
        Tabla2.setBackgoundHover(new java.awt.Color(29, 30, 51));
        Tabla2.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        Tabla2.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        Tabla2.setSelectionBackground(new java.awt.Color(29, 30, 91));
        jScrollPane3.setViewportView(Tabla2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 1220, 520));

        Tabla3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Tabla3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "43532", "silla", "Inicio", "43/65/24 ", "12/43/58"},
                {"2", "67864", "mesa", "Proceso", "54/23/65", "74/34/23"},
                {"3", "45683", "mueble ", "finalizando", "12/43/23", "96/23/28"},
                {"4", "73867", "armario", "Proceso", "95/34/50", "34/54/84"},
                {"5", "67594", "cama", "Terminado", "34/45/34", "84/34/39"}
            },
            new String [] {
                "#", "ID", "Nombre_etapa", "Estado", "Fecha_inicio", "Fecha_final"
            }
        ));
        Tabla3.setBackgoundHead(new java.awt.Color(29, 30, 51));
        Tabla3.setBackgoundHover(new java.awt.Color(29, 30, 51));
        Tabla3.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        Tabla3.setColorSecundaryText(new java.awt.Color(0, 0, 0));
        Tabla3.setSelectionBackground(new java.awt.Color(29, 30, 91));
        jScrollPane4.setViewportView(Tabla3);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 1220, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1290, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo1ActionPerformed
    // Mostrar cuadro de diálogo para seleccionar la tabla
    String[] options = {"produccion", "Detalle produccion", "Etapa produccion"};
    int choice = JOptionPane.showOptionDialog(this, "Seleccione una tabla para agregar datos:",
            "Seleccionar Tabla", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE,
            null, options, options[0]);

    if (choice >= 0) {
        DefaultTableModel model = null;
        int rowNumber = 0; // Para almacenar el número de fila

        // Obtener el modelo de la tabla seleccionada
        switch (choice) {
            case 0: // Tabla 1
                model = (DefaultTableModel) Tabla1.getModel();
                rowNumber = model.getRowCount() + 1; // Número de fila
                int randomId1 = generateRandomId(); // Generar ID aleatorio
                String fechaInicio1 = JOptionPane.showInputDialog("Ingrese Fecha de Inicio:");
                String fechaFinal1 = JOptionPane.showInputDialog("Ingrese Fecha Final:");
                String estado1 = JOptionPane.showInputDialog("Ingrese Estado:");
                
                // Agregar la nueva fila a la tabla
                model.addRow(new Object[]{rowNumber, randomId1, fechaInicio1, fechaFinal1, estado1});
                break;

            case 1: // Tabla 2
                model = (DefaultTableModel) Tabla2.getModel();
                rowNumber = model.getRowCount() + 1; // Número de fila
                String cantidad2 = JOptionPane.showInputDialog("Ingrese Cantidad:");
                String dimensiones2 = JOptionPane.showInputDialog("Ingrese Dimensiones:");
                String materiales2 = JOptionPane.showInputDialog("Ingrese Materiales:");
                
                // Agregar la nueva fila a la tabla
                model.addRow(new Object[]{rowNumber, cantidad2, dimensiones2, materiales2});
                break;

            case 2: // Tabla 3
                model = (DefaultTableModel) Tabla3.getModel();
                rowNumber = model.getRowCount() + 1; // Número de fila
                int randomId3 = generateRandomId(); // Generar ID aleatorio
                String nombreEtapa3 = JOptionPane.showInputDialog("Ingrese Nombre de Etapa:");
                String estado3 = JOptionPane.showInputDialog("Ingrese Estado:");
                String fechaInicio3 = JOptionPane.showInputDialog("Ingrese Fecha de Inicio:");
                String fechaFinal3 = JOptionPane.showInputDialog("Ingrese Fecha Final:");
                
                // Agregar la nueva fila a la tabla
                model.addRow(new Object[]{rowNumber, randomId3, nombreEtapa3, estado3, fechaInicio3, fechaFinal3});
                break;
        }
    }
    
    }//GEN-LAST:event_rSButtonMaterialTwo1ActionPerformed

    private void rSTextFieldMaterialIcon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSTextFieldMaterialIcon1ActionPerformed
        filterTables();
    }//GEN-LAST:event_rSTextFieldMaterialIcon1ActionPerformed

    private void rSButtonFlat_new3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonFlat_new3ActionPerformed
    // Ocultar Tabla1 y Tabla3
    jScrollPane3.setVisible(false); // Ocultar Tabla1
    jScrollPane4.setVisible(false); // Ocultar Tabla3

    // Mostrar Tabla2
    jScrollPane2.setVisible(true); // Mostrar Tabla2
    // Revalidar y repaint para actualizar la interfaz
    // Revalidar y repaint para actualizar la interfaz
    jPanel1.revalidate();
    jPanel1.repaint();
                                                 
    }//GEN-LAST:event_rSButtonFlat_new3ActionPerformed

    private void rSButtonFlat_new1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonFlat_new1ActionPerformed
// Ocultar Tabla1 y Tabla3
    jScrollPane2.setVisible(false); // Ocultar Tabla1
    jScrollPane4.setVisible(false); // Ocultar Tabla3

    // Mostrar Tabla2
    jScrollPane3.setVisible(true); // Mostrar Tabla2
    // Revalidar y repaint para actualizar la interfaz
    // Revalidar y repaint para actualizar la interfaz
    jPanel1.revalidate();
    jPanel1.repaint();
                   // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonFlat_new1ActionPerformed

    private void rSButtonFlat_new2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonFlat_new2ActionPerformed
// Ocultar Tabla1 y Tabla3
    jScrollPane2.setVisible(false); // Ocultar Tabla1
    jScrollPane3.setVisible(false); // Ocultar Tabla3

    // Mostrar Tabla2
    jScrollPane4.setVisible(true); // Mostrar Tabla2
    // Revalidar y repaint para actualizar la interfaz
    // Revalidar y repaint para actualizar la interfaz
    jPanel1.revalidate();
    jPanel1.repaint();
                   // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonFlat_new2ActionPerformed

    private void rSButtonMaterialTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialTwo3ActionPerformed
        // Determinar qué tabla está visible
    DefaultTableModel model = null;
    JTable currentTable = null;

    if (jScrollPane2.isVisible()) {
        model = (DefaultTableModel) Tabla1.getModel();
        currentTable = Tabla1;
    } else if (jScrollPane3.isVisible()) {
        model = (DefaultTableModel) Tabla2.getModel();
        currentTable = Tabla2;
    } else if (jScrollPane4.isVisible()) {
        model = (DefaultTableModel) Tabla3.getModel();
        currentTable = Tabla3;
    }

    // Verificar si hay una fila seleccionada
    int selectedRow = currentTable.getSelectedRow();
    if (selectedRow != -1) { // Si hay una fila seleccionada
        // Confirmar la eliminación
        int confirm = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar esta fila?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // Eliminar la fila seleccionada
            model.removeRow(selectedRow);
            // Actualizar la columna "#" para mantener la secuencia
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(i + 1, i, 0); // Actualiza la columna "#" con el nuevo índice
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila para eliminar.", "No se seleccionó ninguna fila", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_rSButtonMaterialTwo3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSTableMetroCustom Tabla1;
    private RSMaterialComponent.RSTableMetroCustom Tabla2;
    private RSMaterialComponent.RSTableMetroCustom Tabla3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private newscomponents.RSButtonFlat_new rSButtonFlat_new1;
    private newscomponents.RSButtonFlat_new rSButtonFlat_new2;
    private newscomponents.RSButtonFlat_new rSButtonFlat_new3;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo1;
    private RSMaterialComponent.RSButtonMaterialTwo rSButtonMaterialTwo3;
    private RSMaterialComponent.RSTextFieldMaterialIcon rSTextFieldMaterialIcon1;
    // End of variables declaration//GEN-END:variables

    private int generateRandomId() {
        Random random = new Random();
        return 10000 + random.nextInt(90000); // Genera un número entre 10000 y 99999
    }

    private void filterTables() {
    String searchText = rSTextFieldMaterialIcon1.getText().toLowerCase(); // Obtener el texto de búsqueda

    // Filtrar cada tabla
    if (searchText.length() == 1) {
        // Filtrar por la columna "#" (índice 0)
        filterTable(Tabla1, searchText, 0); // Cambia 0 por el índice de la columna "#" en Tabla1
        filterTable(Tabla2, searchText, 0); // Cambia 0 por el índice de la columna "#" en Tabla2
        filterTable(Tabla3, searchText, 0); // Cambia 0 por el índice de la columna "#" en Tabla3
    } else if (searchText.length() >= 2) {
        // Filtrar en todas las columnas
        filterTable(Tabla1, searchText, -1); // Mostrar todas las filas en Tabla1
        filterTable(Tabla2, searchText, -1); // Mostrar todas las filas en Tabla2
        filterTable(Tabla3, searchText, -1); // Mostrar todas las filas en Tabla3
    } else {
        // Si no hay texto, mostrar todas las filas
        filterTable(Tabla1, "", -1); // Mostrar todas las filas en Tabla1
        filterTable(Tabla2, "", -1); // Mostrar todas las filas en Tabla2
        filterTable(Tabla3, "", -1); // Mostrar todas las filas en Tabla3
    }
}

private void filterTable(JTable table, String searchText, int columnIndex) {
    DefaultTableModel model = (DefaultTableModel) table.getModel(); // Obtener el modelo de la tabla
    TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model); // Crear un sorter para la tabla
    table.setRowSorter(sorter); // Establecer el sorter en la tabla

    // Filtrar las filas
    if (searchText.trim().isEmpty()) {
        sorter.setRowFilter(null); // Si no hay texto, mostrar todas las filas
    } else {
        // Filtrar en la columna especificada o en todas las columnas si columnIndex es -1
        if (columnIndex == -1) {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + Pattern.quote(searchText))); // Filtrar en todas las columnas
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + Pattern.quote(searchText), columnIndex)); // Filtrar en la columna especificada
        }
    }
}
}







