/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista;

import java.awt.Frame;
import java.time.Clock;
import javax.swing.JFrame;

/**
 *
 * @author pc
 */
public class tresProduccion extends javax.swing.JDialog {

    
    private Produccion produccionPanel;
    private Produccion produccionPanel2;

    /**
     * Creates new form tresProduccion
     */
    public tresProduccion(Frame parent, boolean modal, Produccion produccionPanel) {
    super(parent, modal);
    this.produccionPanel = produccionPanel;
    initComponents();
setLocationRelativeTo(parent);
    }
    tresProduccion(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelP = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        produccion = new rojeru_san.RSButtonRiple();
        etapacrear = new rojeru_san.RSButtonRiple();
        detallecrear = new rojeru_san.RSButtonRiple();
        volver = new rojeru_san.RSButtonRiple();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelP.setBackground(new java.awt.Color(255, 255, 255));
        panelP.setPreferredSize(new java.awt.Dimension(500, 500));
        panelP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 49, 82));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century751 BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Produccion");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        panelP.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 50));

        produccion.setBackground(new java.awt.Color(46, 49, 82));
        produccion.setText("Produccion");
        produccion.setColorHover(new java.awt.Color(200, 200, 200));
        produccion.setFont(new java.awt.Font("Humnst777 BlkCn BT", 1, 14)); // NOI18N
        produccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                produccionActionPerformed(evt);
            }
        });
        panelP.add(produccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 140, -1));

        etapacrear.setBackground(new java.awt.Color(46, 49, 82));
        etapacrear.setText("Etapa");
        etapacrear.setColorHover(new java.awt.Color(200, 200, 200));
        etapacrear.setFont(new java.awt.Font("Humnst777 BlkCn BT", 1, 14)); // NOI18N
        etapacrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etapacrearActionPerformed(evt);
            }
        });
        panelP.add(etapacrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 140, -1));

        detallecrear.setBackground(new java.awt.Color(46, 49, 82));
        detallecrear.setText("Detalle ");
        detallecrear.setColorHover(new java.awt.Color(200, 200, 200));
        detallecrear.setFont(new java.awt.Font("Humnst777 BlkCn BT", 1, 14)); // NOI18N
        detallecrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detallecrearActionPerformed(evt);
            }
        });
        panelP.add(detallecrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 140, -1));

        volver.setBackground(new java.awt.Color(46, 49, 82));
        volver.setText("Cancelar");
        volver.setColorHover(new java.awt.Color(200, 200, 200));
        volver.setFont(new java.awt.Font("Humnst777 BlkCn BT", 1, 14)); // NOI18N
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        panelP.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelP, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelP, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void produccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_produccionActionPerformed
        this.dispose();
        formuProduccion dialog = new formuProduccion(new javax.swing.JFrame(), true, this.produccionPanel);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_produccionActionPerformed

    private void etapacrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etapacrearActionPerformed
        this.dispose();
        EtapaProduccion dialog = new EtapaProduccion(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_etapacrearActionPerformed

    private void detallecrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detallecrearActionPerformed
         this.dispose();
        // Usa produccionPanel (no produccionPanel2)
        DetalleProduccion dialog = new DetalleProduccion(
            (javax.swing.JFrame) this.getParent(), 
            true, 
            this.produccionPanel
        );
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
      
    }//GEN-LAST:event_detallecrearActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tresProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tresProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tresProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tresProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tresProduccion dialog = new tresProduccion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple detallecrear;
    private rojeru_san.RSButtonRiple etapacrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelP;
    private rojeru_san.RSButtonRiple produccion;
    private rojeru_san.RSButtonRiple volver;
    // End of variables declaration//GEN-END:variables

    
}
